server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

# Internationalization
spring.messages.basename: messages/messages

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    loadbalancer:
      enabled: false
eureka:
  client:
    enabled: false
